### ISSUE TITLE
`DAGMC_LIBRARIES` CMake variable incorrectly populated

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC#642] opened 2019-10-05 00:24 UTC
**Describe the Bug**<br/>
Currently, all libraries are added to the `DAGMC_LIBRARIES` CMake variable whether they are enabled or not. This is caused by [these lines](https://github.com/svalinn/DAGMC/blob/8b23e5fd12dfa59e490a661a054b92722db56f18/cmake/DAGMC_macros.cmake#L225). As these macros get evaluated and inserted into the various directories where it is called, the `DAGMC_LIBRARIES` variable is populated regardless of whether or not the library is enabled or disabled. [`add_subdirectory`](https://cmake.org/cmake/help/v3.0/command/add_subdirectory.html) will keep targets from being added to the project, but the subdirectory `CMakeLists.txt` file will still be processed.

**To Reproduce**<br/>
Clone the repo and run `cmake <dagmc_src_dir> -DBUILD_TALLY=OFF`. You will still see `dagtally` in the list of DAGMC libraries in the `DAGMCConfig.cmake` file in the directory where you've run this command.

**Expected Behavior**<br/>
Only enabled libraries are added to the `DAGMC_LIBRARIES` variable.

**Comment by pshriwise** [comment] 2019-10-05 00:28
@ljacobson64 this is your area of expertise. Any suggestions on how we might update the macro to fix this? We could place these additions to `DAGMC_LIBRARIES` inside of if statements for the different libraries in the `/src/CMakeLists.txt` but there might be a more elegant solution?

**Comment by gonuke** [comment] 2019-10-06 15:06
I think this is addressed in #634 which is stalled trying to sort out whether MOAB's build system is self-consistent across different options.   At this point, I think a CMake build of MOAB will give correct settings and indications for our DAGMC build.

**Comment by pshriwise** [comment] 2019-10-06 21:58
Oh I thought #634 was about managing `MOAB_LIBRARIES`. This issue is entirely internal to DAGMC.

**Comment by ljacobson64** [comment] 2019-10-08 19:17
I was not able to reproduce this behavior. I built DAGMC with `-DBUILD_TALLY=OFF` and this line appeared in `DAGMCConfig.cmake`:
```
set(DAGMC_LIBRARIES MOAB dagmc pyne_dagmc uwuw makeWatertight)
```
`dagtally` is not present.

**Comment by pshriwise** [comment] 2019-10-08 20:03
Hrmm this might be caused by something other than what I initially thought.

Can you running (in the same build directory):

```bash

$ cmake ../dagmc_src -DMOAB_DIR=...
$ cmake ../dagmc_src -DMOAB_DIR=... -DBUILD_TALLY=OFF
```
When I do this I see that many libraries are listed twice and that `dagtally` is still among them.  Could this have to do with some of the CMake flags on the `DAGMC_LIBRARIES` variable?

**Comment by ljacobson64** [comment] 2019-10-08 20:11
I see that too. It says
```
set(DAGMC_LIBRARIES MOAB dagmc pyne_dagmc uwuw dagtally makeWatertight dagmc pyne_dagmc uwuw makeWatertight)
```

In general I would recommend clearing the build directory before re-running cmake, but this is probably something we should fix anyways.

**Comment by pshriwise** [comment] 2019-10-08 20:13
Agreed. If we don't cache that variable, the only library I get in that list is `MOAB` :disappointed: 

I'll read up a bit on solutions. Let me know if you find anything too.

**Comment by gonuke** [comment] 2021-07-23 21:02
#643 claims to address this

**Closed as completed by gonuke** 2021-07-23 21:02 UTC
Labels: Type: Defect
